import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CuteStar from "./components/CuteStar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          minHeight: "100vh",
          overflowX: "hidden",
          position: 'relative',
        }}
      >
        {/* Animated stars in the background */}
        <div
          aria-hidden
          style={{
            position: "fixed",
            inset: 0,
            pointerEvents: "none",
            zIndex: 0,
            width: '100vw',
            height: '100vh',
            overflow: 'hidden',
          }}
        >
          <CuteStar style={{ position: 'absolute', left: 140, top: 180, opacity: 0.55, zIndex: 0, width: 48, height: 48, filter: 'blur(0.2px)', animation: 'starFloat1 8s ease-in-out infinite alternate' }} />
          <CuteStar style={{ position: 'absolute', right: 80, top: 60, opacity: 0.45, zIndex: 0, width: 38, height: 38, filter: 'blur(0.4px)', animation: 'starFloat2 10s ease-in-out infinite alternate' }} />
          <CuteStar style={{ position: 'absolute', left: 200, bottom: 100, opacity: 0.5, zIndex: 0, width: 42, height: 42, filter: 'blur(0.3px)', animation: 'starFloat3 9s ease-in-out infinite alternate' }} />
          <CuteStar style={{ position: 'absolute', right: 200, bottom: 120, opacity: 0.48, zIndex: 0, width: 54, height: 54, filter: 'blur(0.5px)', animation: 'starFloat4 11s ease-in-out infinite alternate' }} />
          <CuteStar style={{ position: 'absolute', left: '60%', top: 40, opacity: 0.42, zIndex: 0, width: 36, height: 36, transform: 'translateX(-50%)', filter: 'blur(0.6px)', animation: 'starFloat5 13s ease-in-out infinite alternate' }} />
        </div>
        {children}
        <style>{`
          @keyframes starFloat1 {
            0% { transform: scale(1) rotate(-8deg); }
            100% { transform: translateY(-18px) scale(1.08) rotate(8deg); }
          }
          @keyframes starFloat2 {
            0% { transform: scale(1) rotate(6deg); }
            100% { transform: translateX(22px) scale(1.12) rotate(-6deg); }
          }
          @keyframes starFloat3 {
            0% { transform: scale(1) rotate(0deg); }
            100% { transform: translateY(16px) scale(1.09) rotate(10deg); }
          }
          @keyframes starFloat4 {
            0% { transform: scale(1) rotate(-4deg); }
            100% { transform: translateX(-18px) scale(1.13) rotate(4deg); }
          }
          @keyframes starFloat5 {
            0% { transform: translateX(-50%) scale(1) rotate(0deg); }
            100% { transform: translateX(-50%) translateY(-20px) scale(1.11) rotate(-8deg); }
          }
        `}</style>
      </body>
    </html>
  );
}
